# Generated by Django 4.2.7 on 2023-12-12 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_course_vietnam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vietnam_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
